NSTALLED_APPS = [
    ...
    'django.contrib.auth',   #Core authentication framework and its default models.
     'django.contrib.contenttypes', # Django content type system (allows permissions to be associated with models).
    ....

MIDDLEWARE = [
    ...
    'django.contrib.sessions.middleware.SessionMiddleware',   #Manages sessions across requests
    ...
    'django.contrib.auth.middleware.AuthenticationMiddleware',   #Associates users with requests using sessions.
    ....
