# Generated by Django 2.1.8 on 2020-01-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
